import type { Page } from "~/types/Page";

export const usePagesStore = defineStore('pages', () => {
  const pages = ref<Page[]>([
    {
      id: 1,
      parentId: 0,
      url: '/',
      title: 'Home',
      fileName: 'Home',
      metaDescription: '',
      content: [],
      icon: null,
      contentComponent: null,
      createdBy: 'Dmitry Bite',
      createdAt: '2024-10-15 02:10:03',
      updatedAt: '2024-10-16 02:30:03'
    },
    {
      id: 2,
      parentId: 1,
      url: '/about',
      title: 'About',
      fileName: 'About',
      metaDescription: '',
      content: [],
      icon: 'Folder',
      contentComponent: null,
      showInFinder: true,
      createdBy: 'Dmitry Bite',
      createdAt: '2024-10-17 03:15:21',
      updatedAt: '2024-10-18 04:25:18'
    },
    {
      id: 7,
      parentId: 1,
      url: '/services',
      title: 'Услуги',
      fileName: 'Услуги',
      metaDescription: '',
      content: [],
      icon: 'Folder',
      contentComponent: null,
      showInFinder: true,
      createdBy: 'Dmitry Bite',
      createdAt: '2024-10-19 05:50:03',
      updatedAt: '2024-10-20 06:15:47'
    },
    {
      id: 3,
      parentId: 1,
      url: '/events',
      title: 'Эвенты',
      fileName: 'События',
      metaDescription: '',
      content: [],
      icon: 'Folder',
      contentComponent: null,
      showInFinder: true,
      createdBy: 'Dmitry Bite',
      createdAt: '2024-10-21 07:40:12',
      updatedAt: '2024-10-22 08:30:03'
    },
    {
      id: 9,
      parentId: 1,
      url: '/gallery',
      title: 'Фотки',
      fileName: 'Фотографии',
      metaDescription: '',
      content: [],
      contentComponent: {
        directory: 'Gallery/',
        component: 'ImageGallery'
      },
      icon: 'Camera',
      showInFinder: true,
      createdBy: 'Dmitry Bite',
      createdAt: '2024-10-23 09:10:53',
      updatedAt: '2024-10-24 10:11:21'
    },
    {
      id: 4,
      parentId: 1,
      url: '/games',
      title: 'Игры',
      fileName: 'Игры',
      metaDescription: '',
      content: [],
      contentComponent: null,
      icon: 'Gamepad2',
      showInFinder: true,
      createdBy: 'Dmitry Bite',
      createdAt: '2024-10-25 11:15:03',
      updatedAt: '2024-10-26 12:23:45'
    },
    {
      id: 5,
      parentId: 1,
      url: '/consoles',
      title: 'Консоли',
      fileName: 'Приставки',
      metaDescription: '',
      content: [],
      contentComponent: null,
      icon: 'Computer',
      showInFinder: true,
      createdBy: 'Dmitry Bite',
      createdAt: '2024-10-27 13:04:32',
      updatedAt: '2024-10-28 14:30:23'
    },
    {
      id: 6,
      parentId: 1,
      url: '/movies',
      title: 'Кинцо',
      fileName: 'Кинозал и VHS',
      metaDescription: '',
      content: [],
      contentComponent: null,
      icon: 'Film',
      showInFinder: true,
      createdBy: 'Dmitry Bite',
      createdAt: '2024-10-29 15:10:41',
      updatedAt: '2024-10-30 16:20:12'
    },
    {
      id: 8,
      parentId: 1,
      url: '/contacts',
      title: 'Контакты',
      fileName: 'Контакты',
      metaDescription: '',
      content: [],
      icon: 'Folder',
      contentComponent: null,
      showInFinder: true,
      createdBy: 'Dmitry Bite',
      createdAt: '2024-10-31 17:00:03',
      updatedAt: '2024-11-01 18:10:19'
    },
    {
      id: 10,
      parentId: 3,
      url: '/retro-playground-party-1',
      title: 'Retro Playground Party vol.1',
      fileName: 'Retro Playground Party vol.1',
      metaDescription: '',
      content: [],
      icon: 'Swords',
      createdBy: 'Dmitry Bite',
      createdAt: '2024-11-02 19:15:43',
      updatedAt: '2024-11-03 20:17:52'
    },
    {
      id: 11,
      parentId: 3,
      url: '/retro-playground-party-2',
      title: 'Retro Playground Party vol.2',
      fileName: 'Retro Playground Party vol.2',
      metaDescription: '',
      content: [],
      contentComponent: null,
      icon: 'Joystick',
      createdBy: 'Dmitry Bite',
      createdAt: '2024-11-04 21:30:14',
      updatedAt: '2024-11-05 22:32:43'
    },
    {
      id: 12,
      parentId: 2,
      url: '/history',
      title: 'История создания',
      fileName: 'История',
      metaDescription: '',
      content: [],
      contentComponent: null,
      icon: 'FileType2',
      createdBy: 'Dmitry Bite',
      createdAt: '2024-11-06 23:45:01',
      updatedAt: '2024-11-07 00:50:03'
    },
    {
      id: 13,
      parentId: 2,
      url: '/rules',
      title: 'Наши правила',
      fileName: 'Правила',
      metaDescription: '',
      content: [],
      contentComponent: null,
      icon: 'FileText',
      createdBy: 'Dmitry Bite',
      createdAt: '2024-11-08 01:11:03',
      updatedAt: '2024-11-09 02:20:15'
    },
    {
      id: 14,
      parentId: 3,
      url: '/retro-playground-party-3',
      title: 'Retro Playground Party vol.3',
      fileName: 'Retro Playground Party vol.3',
      metaDescription: '',
      content: [],
      contentComponent: null,
      icon: 'FileHeart',
      createdBy: 'Dmitry Bite',
      createdAt: '2024-11-10 03:25:34',
      updatedAt: '2024-11-11 04:30:42'
    },
    {
      id: 15,
      parentId: 3,
      url: '/retro-playground-party-4',
      title: 'Retro Playground Party vol.4',
      fileName: 'Retro Playground Party vol.4',
      metaDescription: '',
      content: [],
      contentComponent: null,
      icon: 'Atom',
      createdBy: 'Dmitry Bite',
      createdAt: '2024-11-12 05:40:52',
      updatedAt: '2024-11-13 06:10:23'
    },
    {
      id: 16,
      parentId: 3,
      url: '/retro-playground-party-5',
      title: 'Retro Playground Party vol.5',
      fileName: 'Retro Playground Party vol.5',
      metaDescription: '',
      content: [],
      contentComponent: null,
      icon: 'PartyPopper',
      createdBy: 'Dmitry Bite',
      createdAt: '2024-11-14 07:50:01',
      updatedAt: '2024-11-15 08:30:35'
    },
    {
      id: 17,
      parentId: 3,
      url: '/retro-playground-party-6',
      title: 'Retro Playground Party vol.6',
      fileName: 'Retro Playground Party vol.6',
      metaDescription: '',
      content: [],
      contentComponent: null,
      icon: 'Gamepad',
      createdBy: 'Dmitry Bite',
      createdAt: '2024-11-16 09:15:11',
      updatedAt: '2024-11-17 10:05:27'
    },
    {
      id: 18,
      parentId: 3,
      url: '/retro-playground-party-7',
      title: 'Retro Playground Party vol.7',
      fileName: 'Retro Playground Party vol.7',
      metaDescription: '',
      content: [],
      contentComponent: null,
      icon: 'Dices',
      createdBy: 'Dmitry Bite',
      createdAt: '2024-11-18 11:30:33',
      updatedAt: '2024-11-19 12:20:11'
    },
    {
      id: 19,
      parentId: 3,
      url: '/retro-playground-party-8',
      title: 'Retro Playground Party vol.8',
      fileName: 'Retro Playground Party vol.8',
      metaDescription: '',
      content: [],
      contentComponent: null,
      icon: 'Gamepad2',
      createdBy: 'Dmitry Bite',
      createdAt: '2024-11-20 13:50:22',
      updatedAt: '2024-11-21 14:30:09'
    },
    {
      id: 20,
      parentId: 8,
      url: '/location',
      title: 'Карта',
      fileName: 'Карта',
      metaDescription: '',
      icon: 'MapPinned',
      content: [],
      contentComponent: {
        directory: 'Contacts/',
        component: 'MapComponent'
      },
      hideStatusBar: true,
      createdBy: 'Dmitry Bite',
      createdAt: '2024-11-22 15:10:45',
      updatedAt: '2024-11-23 16:05:03'
    },
    {
      id: 21,
      parentId: 8,
      url: '/feedback-form',
      title: 'Обратная связь',
      fileName: 'Написать нам',
      metaDescription: '',
      icon: 'Mail',
      content: [],
      contentComponent: {
        directory: 'Contacts/',
        component: 'FeedbackForm'
      },
      hideStatusBar: true,
      resetWidth: true,
      createdBy: 'Dmitry Bite',
      createdAt: '2024-11-24 17:10:33',
      updatedAt: '2024-11-25 18:20:29'
    },
    {
      id: 22,
      parentId: 4,
      url: '/rpg',
      title: 'RPG',
      fileName: 'RPG',
      metaDescription: '',
      content: [],
      contentComponent: null,
      icon: 'Folder',
      showInFinder: true,
      createdBy: 'Dmitry Bite',
      createdAt: '2024-11-26 19:05:03',
      updatedAt: '2024-11-27 20:50:33'
    },
    {
      id: 23,
      parentId: 4,
      url: '/action',
      title: 'Action',
      fileName: 'Action',
      metaDescription: '',
      content: [],
      contentComponent: null,
      icon: 'Folder',
      showInFinder: true,
      createdBy: 'Dmitry Bite',
      createdAt: '2024-11-28 21:30:03',
      updatedAt: '2024-11-29 22:45:19'
    },
    {
      id: 27,
      parentId: 4,
      url: '/arcade',
      title: 'Arcade',
      fileName: 'Arcade',
      metaDescription: '',
      content: [],
      contentComponent: null,
      icon: 'Folder',
      showInFinder: true,
      createdBy: 'Dmitry Bite',
      createdAt: '2024-12-01 23:10:23',
      updatedAt: '2024-12-02 00:20:35'
    },
    {
      id: 28,
      parentId: 4,
      url: '/fps',
      title: 'FPS',
      fileName: 'FPS',
      metaDescription: '',
      content: [],
      contentComponent: null,
      icon: 'Folder',
      showInFinder: true,
      createdBy: 'Dmitry Bite',
      createdAt: '2024-12-03 01:15:09',
      updatedAt: '2024-12-04 02:10:45'
    },
    {
      id: 29,
      parentId: 4,
      url: '/quest',
      title: 'Quest',
      fileName: 'Quest',
      metaDescription: '',
      content: [],
      contentComponent: null,
      icon: 'Folder',
      showInFinder: true,
      createdBy: 'Dmitry Bite',
      createdAt: '2024-12-04 07:33:21',
      updatedAt: '2024-12-05 08:34:39'
    },
    {
      id: 33,
      parentId: 4,
      url: '/file/readme.txt',
      title: 'readme.txt',
      fileName: 'readme.txt',
      metaDescription: '',
      content: [],
      contentComponent: null,
      icon: 'FileText',
      createdBy: 'Dmitry Bite',
      createdAt: '2024-12-06 09:14:25',
      updatedAt: '2024-12-07 10:15:50'
    },
    {
      id: 30,
      parentId: 4,
      url: '/racing',
      title: 'Racing',
      fileName: 'Racing',
      metaDescription: '',
      content: [],
      contentComponent: null,
      icon: 'Folder',
      showInFinder: true,
      createdBy: 'Dmitry Bite',
      createdAt: '2024-12-08 11:00:53',
      updatedAt: '2024-12-09 12:11:23'
    },
    {
      id: 31,
      parentId: 4,
      url: '/simulator',
      title: 'Simulator',
      fileName: 'Simulator',
      metaDescription: '',
      content: [],
      contentComponent: null,
      icon: 'Folder',
      showInFinder: true,
      createdBy: 'Dmitry Bite',
      createdAt: '2024-12-10 13:10:34',
      updatedAt: '2024-12-11 14:20:15'
    },
    {
      id: 32,
      parentId: 4,
      url: '/strategy',
      title: 'Strategy',
      fileName: 'Strategy',
      metaDescription: '',
      content: [],
      contentComponent: null,
      icon: 'Folder',
      showInFinder: true,
      createdBy: 'Dmitry Bite',
      createdAt: '2024-12-12 15:30:12',
      updatedAt: '2024-12-13 16:35:27'
    },
    {
      id: 34,
      parentId: 22,
      url: '/fallout',
      title: 'Fallout',
      fileName: 'Fallout',
      metaDescription: '',
      content: [],
      contentComponent: null,
      icon: 'AppWindow',
      createdBy: 'Dmitry Bite',
      createdAt: '2024-12-14 17:10:33',
      updatedAt: '2024-12-15 18:30:03'
    },
    {
      id: 35,
      parentId: 22,
      url: '/fallout2',
      title: 'Fallout 2',
      fileName: 'fallout2.html',
      metaDescription: '',
      content: {
        id: 1,
        pageId: 35,
        h1: 'War. War never changes...',
        blocks: [
          {
            id: 1,
            type: 'text',
            title: 'Путешествие в постъядерный мир, который ждет тебя снова.',
            img: '/images/games/fallout2/fallout_2.webp',
            p: [
              'Прошло 20 лет, и воспоминания о Fallout 2 уже покрылись пылью, как руины довоенного мира. Но эта игра не просто устояла перед временем – она по-прежнему задает планку для ролевых игр с открытым миром.',
              'Ты помнишь это чувство свободы? Когда можно было быть кем угодно – бесстрашным искателем приключений, хитрым дипломатом или беспощадным охотником за головами. Здесь нет навязанных решений, только ты и твой путь. Ты сам выбираешь, как выжить – миром или силой.',
              'Помнишь атмосферу? Глухие пустоши, наполненные таинственными встречами, жестокими схватками и черным юмором, который до сих пор не устарел. Fallout 2 – это не просто игра, это живая вселенная, где твои решения имеют последствия. Здесь нет линейных заданий – только твоя история, написанная поступками.',
              'Игра ждет тебя. Ты был там раньше, но увидишь мир совсем по-другому. Прокачай своего Избранного, отправься в путь и вспомни, за что мы все так любили эту классику. Пустоши не изменились...'
            ],
            images: [
              '/images/games/fallout2/1.png', '/images/games/fallout2/2.png', '/images/games/fallout2/3.png',
            ]
          },
          {
            id: 2,
            type: 'text',
            title: 'Ты там еще не был? Самое время отправиться в путь!',
            p: [
              'Добро пожаловать в мир, где цивилизация пала, а надежда осталась лишь у тех, кто достаточно силен или умен, чтобы выжить. Здесь каждый встречный может стать другом или врагом, а каждое твое решение определяет, каким будет твое путешествие.',
              'Fallout 2 – это не просто приключение, это испытание. Готов ли ты прокладывать себе путь в мире, где законы диктует не власть, а сила? Где вместо денег – крышки, а старые технологии стали дороже золота? Где одна неосторожная фраза может стоить тебе жизни, а удачная сделка откроет двери к новым возможностям?',
              'Ты можешь стать дипломатом, убеждая людей словами, или пустить в ход оружие, решая проблемы иначе. Здесь нет заранее написанного сценария – только ты и твоя история.',
              'Добавь к этому фирменный черный юмор, колоритных персонажей, опасные локации и мир, который не прощает ошибок. Fallout 2 – это путешествие, которое ты точно не забудешь. Этот мир уже изменил тысячи жизней. Может, теперь твоя очередь?'
            ],
            images: [
              '/images/games/fallout2/4.png', '/images/games/fallout2/5.png', '/images/games/fallout2/6.png', '/images/games/fallout2/7.png'
            ]
          }
        ]
      },
      contentComponent: null,
      icon: 'AppWindow',
      createdBy: 'Dmitry Bite',
      createdAt: '2024-12-16 19:30:03',
      updatedAt: '2024-12-17 20:40:12'
    },
    {
      id: 36,
      parentId: 1,
      url: '/desktop',
      title: 'Desktop',
      fileName: 'Desktop',
      metaDescription: '',
      content: [],
      contentComponent: null,
      icon: 'Folder',
      showInFinder: false,
      createdBy: 'Dmitry Bite',
      createdAt: '2024-12-18 21:10:45',
      updatedAt: '2024-12-19 22:15:17'
    },
    {
      id: 37,
      parentId: 1,
      url: '/my-computer',
      title: 'My computer',
      fileName: 'My computer',
      icon: 'Laptop2',
      metaDescription: '',
      content: [],
      contentComponent: null,
      showInFinder: false,
      createdBy: 'Dmitry Bite',
      createdAt: '2024-12-20 23:35:25',
      updatedAt: '2024-12-21 00:50:15'
    },
    {
      id: 38,
      parentId: 1,
      url: '/trash',
      title: 'Trash',
      fileName: 'Trash',
      icon: 'Trash2',
      metaDescription: '',
      content: [],
      contentComponent: null,
      showInFinder: false,
      createdBy: 'Dmitry Bite',
      createdAt: '2024-12-22 01:15:38',
      updatedAt: '2024-12-23 02:05:19'
    }
  ])
  
  const isLoaded = ref<boolean>(false)
  const loading = ref<boolean>(false)

  return { pages }
})
