import type { Page } from "~/types/Page";

export const usePagesStore = defineStore('pages', () => {
  const pages = ref<Page[]>([
    {
      id: 1,
      parentId: 0,
      url: '/',
      title: 'Home',
      h1: 'Home',
      metaDescription: '',
      content: [],
      icon: null,
      contentComponent: null,
      createdBy: 'Dmitry Bite',
      createdAt: '2024-10-15 02:10:03',
      updatedAt: '2024-10-16 02:30:03'
    },
    {
      id: 2,
      parentId: 1,
      url: '/about',
      title: 'About',
      h1: 'О клубе',
      metaDescription: '',
      content: [],
      icon: 'Folder',
      contentComponent: null,
      showInFinder: true,
      createdBy: 'Dmitry Bite',
      createdAt: '2024-10-17 03:15:21',
      updatedAt: '2024-10-18 04:25:18'
    },
    {
      id: 7,
      parentId: 1,
      url: '/services',
      title: 'Услуги',
      h1: 'Услуги',
      metaDescription: '',
      content: [],
      icon: 'Folder',
      contentComponent: null,
      showInFinder: true,
      createdBy: 'Dmitry Bite',
      createdAt: '2024-10-19 05:50:03',
      updatedAt: '2024-10-20 06:15:47'
    },
    {
      id: 3,
      parentId: 1,
      url: '/events',
      title: 'Эвенты',
      h1: 'События',
      metaDescription: '',
      content: [],
      icon: 'Folder',
      contentComponent: null,
      showInFinder: true,
      createdBy: 'Dmitry Bite',
      createdAt: '2024-10-21 07:40:12',
      updatedAt: '2024-10-22 08:30:03'
    },
    {
      id: 9,
      parentId: 1,
      url: '/gallery',
      title: 'Фотки',
      h1: 'Фотографии',
      metaDescription: '',
      content: [],
      contentComponent: {
        directory: 'Gallery/',
        component: 'ImageGallery'
      },
      icon: 'Camera',
      showInFinder: true,
      createdBy: 'Dmitry Bite',
      createdAt: '2024-10-23 09:10:53',
      updatedAt: '2024-10-24 10:11:21'
    },
    {
      id: 4,
      parentId: 1,
      url: '/games',
      title: 'Игры',
      h1: 'Игры',
      metaDescription: '',
      content: [],
      contentComponent: null,
      icon: 'Gamepad2',
      showInFinder: true,
      createdBy: 'Dmitry Bite',
      createdAt: '2024-10-25 11:15:03',
      updatedAt: '2024-10-26 12:23:45'
    },
    {
      id: 5,
      parentId: 1,
      url: '/consoles',
      title: 'Консоли',
      h1: 'Приставки',
      metaDescription: '',
      content: [],
      contentComponent: null,
      icon: 'Computer',
      showInFinder: true,
      createdBy: 'Dmitry Bite',
      createdAt: '2024-10-27 13:04:32',
      updatedAt: '2024-10-28 14:30:23'
    },
    {
      id: 6,
      parentId: 1,
      url: '/movies',
      title: 'Кинцо',
      h1: 'Кинозал и VHS',
      metaDescription: '',
      content: [],
      contentComponent: null,
      icon: 'Film',
      showInFinder: true,
      createdBy: 'Dmitry Bite',
      createdAt: '2024-10-29 15:10:41',
      updatedAt: '2024-10-30 16:20:12'
    },
    {
      id: 8,
      parentId: 1,
      url: '/contacts',
      title: 'Контакты',
      h1: 'Контакты',
      metaDescription: '',
      content: [],
      icon: 'Folder',
      contentComponent: null,
      showInFinder: true,
      createdBy: 'Dmitry Bite',
      createdAt: '2024-10-31 17:00:03',
      updatedAt: '2024-11-01 18:10:19'
    },
    {
      id: 10,
      parentId: 3,
      url: '/retro-playground-party-1',
      title: 'Retro Playground Party vol.1',
      h1: 'Retro Playground Party vol.1',
      metaDescription: '',
      content: [],
      icon: 'Swords',
      createdBy: 'Dmitry Bite',
      createdAt: '2024-11-02 19:15:43',
      updatedAt: '2024-11-03 20:17:52'
    },
    {
      id: 11,
      parentId: 3,
      url: '/retro-playground-party-2',
      title: 'Retro Playground Party vol.2',
      h1: 'Retro Playground Party vol.2',
      metaDescription: '',
      content: [],
      contentComponent: null,
      icon: 'Joystick',
      createdBy: 'Dmitry Bite',
      createdAt: '2024-11-04 21:30:14',
      updatedAt: '2024-11-05 22:32:43'
    },
    {
      id: 12,
      parentId: 2,
      url: '/history',
      title: 'История создания',
      h1: 'История',
      metaDescription: '',
      content: [],
      contentComponent: null,
      icon: 'FileType2',
      createdBy: 'Dmitry Bite',
      createdAt: '2024-11-06 23:45:01',
      updatedAt: '2024-11-07 00:50:03'
    },
    {
      id: 13,
      parentId: 2,
      url: '/rules',
      title: 'Наши правила',
      h1: 'Правила',
      metaDescription: '',
      content: [],
      contentComponent: null,
      icon: 'FileText',
      createdBy: 'Dmitry Bite',
      createdAt: '2024-11-08 01:11:03',
      updatedAt: '2024-11-09 02:20:15'
    },
    {
      id: 14,
      parentId: 3,
      url: '/retro-playground-party-3',
      title: 'Retro Playground Party vol.3',
      h1: 'Retro Playground Party vol.3',
      metaDescription: '',
      content: [],
      contentComponent: null,
      icon: 'FileHeart',
      createdBy: 'Dmitry Bite',
      createdAt: '2024-11-10 03:25:34',
      updatedAt: '2024-11-11 04:30:42'
    },
    {
      id: 15,
      parentId: 3,
      url: '/retro-playground-party-4',
      title: 'Retro Playground Party vol.4',
      h1: 'Retro Playground Party vol.4',
      metaDescription: '',
      content: [],
      contentComponent: null,
      icon: 'Atom',
      createdBy: 'Dmitry Bite',
      createdAt: '2024-11-12 05:40:52',
      updatedAt: '2024-11-13 06:10:23'
    },
    {
      id: 16,
      parentId: 3,
      url: '/retro-playground-party-5',
      title: 'Retro Playground Party vol.5',
      h1: 'Retro Playground Party vol.5',
      metaDescription: '',
      content: [],
      contentComponent: null,
      icon: 'PartyPopper',
      createdBy: 'Dmitry Bite',
      createdAt: '2024-11-14 07:50:01',
      updatedAt: '2024-11-15 08:30:35'
    },
    {
      id: 17,
      parentId: 3,
      url: '/retro-playground-party-6',
      title: 'Retro Playground Party vol.6',
      h1: 'Retro Playground Party vol.6',
      metaDescription: '',
      content: [],
      contentComponent: null,
      icon: 'Gamepad',
      createdBy: 'Dmitry Bite',
      createdAt: '2024-11-16 09:15:11',
      updatedAt: '2024-11-17 10:05:27'
    },
    {
      id: 18,
      parentId: 3,
      url: '/retro-playground-party-7',
      title: 'Retro Playground Party vol.7',
      h1: 'Retro Playground Party vol.7',
      metaDescription: '',
      content: [],
      contentComponent: null,
      icon: 'Dices',
      createdBy: 'Dmitry Bite',
      createdAt: '2024-11-18 11:30:33',
      updatedAt: '2024-11-19 12:20:11'
    },
    {
      id: 19,
      parentId: 3,
      url: '/retro-playground-party-8',
      title: 'Retro Playground Party vol.8',
      h1: 'Retro Playground Party vol.8',
      metaDescription: '',
      content: [],
      contentComponent: null,
      icon: 'Gamepad2',
      createdBy: 'Dmitry Bite',
      createdAt: '2024-11-20 13:50:22',
      updatedAt: '2024-11-21 14:30:09'
    },
    {
      id: 20,
      parentId: 8,
      url: '/location',
      title: 'Карта',
      h1: 'Карта',
      metaDescription: '',
      icon: 'MapPinned',
      content: [],
      contentComponent: {
        directory: 'Contacts/',
        component: 'MapComponent'
      },
      hideStatusBar: true,
      createdBy: 'Dmitry Bite',
      createdAt: '2024-11-22 15:10:45',
      updatedAt: '2024-11-23 16:05:03'
    },
    {
      id: 21,
      parentId: 8,
      url: '/feedback-form',
      title: 'Обратная связь',
      h1: 'Написать нам',
      metaDescription: '',
      icon: 'Mail',
      content: [],
      contentComponent: {
        directory: 'Contacts/',
        component: 'FeedbackForm'
      },
      hideStatusBar: true,
      resetWidth: true,
      createdBy: 'Dmitry Bite',
      createdAt: '2024-11-24 17:10:33',
      updatedAt: '2024-11-25 18:20:29'
    },
    {
      id: 22,
      parentId: 4,
      url: '/rpg',
      title: 'RPG',
      h1: 'RPG',
      metaDescription: '',
      content: [],
      contentComponent: null,
      icon: 'Folder',
      showInFinder: true,
      createdBy: 'Dmitry Bite',
      createdAt: '2024-11-26 19:05:03',
      updatedAt: '2024-11-27 20:50:33'
    },
    {
      id: 23,
      parentId: 4,
      url: '/action',
      title: 'Action',
      h1: 'Action',
      metaDescription: '',
      content: [],
      contentComponent: null,
      icon: 'Folder',
      showInFinder: true,
      createdBy: 'Dmitry Bite',
      createdAt: '2024-11-28 21:30:03',
      updatedAt: '2024-11-29 22:45:19'
    },
    {
      id: 27,
      parentId: 4,
      url: '/arcade',
      title: 'Arcade',
      h1: 'Arcade',
      metaDescription: '',
      content: [],
      contentComponent: null,
      icon: 'Folder',
      showInFinder: true,
      createdBy: 'Dmitry Bite',
      createdAt: '2024-12-01 23:10:23',
      updatedAt: '2024-12-02 00:20:35'
    },
    {
      id: 28,
      parentId: 4,
      url: '/fps',
      title: 'FPS',
      h1: 'FPS',
      metaDescription: '',
      content: [],
      contentComponent: null,
      icon: 'Folder',
      showInFinder: true,
      createdBy: 'Dmitry Bite',
      createdAt: '2024-12-03 01:15:09',
      updatedAt: '2024-12-04 02:10:45'
    },
    {
      id: 29,
      parentId: 4,
      url: '/quest',
      title: 'Quest',
      h1: 'Quest',
      metaDescription: '',
      content: [],
      contentComponent: null,
      icon: 'Folder',
      showInFinder: true,
      createdBy: 'Dmitry Bite',
      createdAt: '2024-12-04 07:33:21',
      updatedAt: '2024-12-05 08:34:39'
    },
    {
      id: 33,
      parentId: 4,
      url: '/file/readme.txt',
      title: 'readme.txt',
      h1: 'readme.txt',
      metaDescription: '',
      content: [],
      contentComponent: null,
      icon: 'FileText',
      createdBy: 'Dmitry Bite',
      createdAt: '2024-12-06 09:14:25',
      updatedAt: '2024-12-07 10:15:50'
    },
    {
      id: 30,
      parentId: 4,
      url: '/racing',
      title: 'Racing',
      h1: 'Racing',
      metaDescription: '',
      content: [],
      contentComponent: null,
      icon: 'Folder',
      showInFinder: true,
      createdBy: 'Dmitry Bite',
      createdAt: '2024-12-08 11:00:53',
      updatedAt: '2024-12-09 12:11:23'
    },
    {
      id: 31,
      parentId: 4,
      url: '/simulator',
      title: 'Simulator',
      h1: 'Simulator',
      metaDescription: '',
      content: [],
      contentComponent: null,
      icon: 'Folder',
      showInFinder: true,
      createdBy: 'Dmitry Bite',
      createdAt: '2024-12-10 13:10:34',
      updatedAt: '2024-12-11 14:20:15'
    },
    {
      id: 32,
      parentId: 4,
      url: '/strategy',
      title: 'Strategy',
      h1: 'Strategy',
      metaDescription: '',
      content: [],
      contentComponent: null,
      icon: 'Folder',
      showInFinder: true,
      createdBy: 'Dmitry Bite',
      createdAt: '2024-12-12 15:30:12',
      updatedAt: '2024-12-13 16:35:27'
    },
    {
      id: 34,
      parentId: 22,
      url: '/fallout',
      title: 'Fallout',
      h1: 'Fallout',
      metaDescription: '',
      content: [],
      contentComponent: null,
      icon: 'AppWindow',
      createdBy: 'Dmitry Bite',
      createdAt: '2024-12-14 17:10:33',
      updatedAt: '2024-12-15 18:30:03'
    },
    {
      id: 35,
      parentId: 22,
      url: '/fallout2',
      title: 'Fallout 2',
      h1: 'Fallout 2',
      metaDescription: '',
      content: [],
      contentComponent: null,
      icon: 'AppWindow',
      createdBy: 'Dmitry Bite',
      createdAt: '2024-12-16 19:30:03',
      updatedAt: '2024-12-17 20:40:12'
    },
    {
      id: 36,
      parentId: 1,
      url: '/desktop',
      title: 'Desktop',
      h1: 'Desktop',
      metaDescription: '',
      content: [],
      contentComponent: null,
      icon: 'Folder',
      showInFinder: false,
      createdBy: 'Dmitry Bite',
      createdAt: '2024-12-18 21:10:45',
      updatedAt: '2024-12-19 22:15:17'
    },
    {
      id: 37,
      parentId: 1,
      url: '/my-computer',
      title: 'My computer',
      h1: 'My computer',
      icon: 'Laptop2',
      metaDescription: '',
      content: [],
      contentComponent: null,
      showInFinder: false,
      createdBy: 'Dmitry Bite',
      createdAt: '2024-12-20 23:35:25',
      updatedAt: '2024-12-21 00:50:15'
    },
    {
      id: 38,
      parentId: 1,
      url: '/trash',
      title: 'Trash',
      h1: 'Trash',
      icon: 'Trash2',
      metaDescription: '',
      content: [],
      contentComponent: null,
      showInFinder: false,
      createdBy: 'Dmitry Bite',
      createdAt: '2024-12-22 01:15:38',
      updatedAt: '2024-12-23 02:05:19'
    }
  ])
  
  const isLoaded = ref<boolean>(false)
  const loading = ref<boolean>(false)

  return { pages }
})
